import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';

const PAGE_TITLES = {
  '/tableau-de-bord': 'Tableau de Bord',
  '/vaisseaux': 'Base de Données Vaisseaux — 150+ Ships Star Citizen',
  '/vaisseaux/comparer': 'Comparateur de Vaisseaux',
  '/flotte': 'Gestionnaire de Flotte',
  '/flotte/analyse': 'Analyse de Flotte',
  '/commerce': 'Planificateur Commerce — Routes & Prix Live',
  '/commerce/cargo': 'Optimiseur Cargo',
  '/commerce/calculateur': 'Calculateur Commerce',
  '/routes': 'Optimiseur de Routes',
  '/missions': 'Planificateur de Missions',
  '/missions/base': 'Base de Données Missions',
  '/missions/empilement': 'Empilement de Missions',
  '/missions/tracker': 'Suivi de Missions',
  '/missions/calculateur': 'Calculateur de Missions',
  '/systemes': 'Systèmes Stellaires — Stanton & Pyro',
  '/systemes/planetes': 'Planètes & Lunes',
  '/systemes/stations': 'Carte des Stations',
  '/fabricants': 'Fabricants de Vaisseaux',
  '/factions': 'Factions & Organisations',
  '/guides': 'Guides Gameplay Star Citizen',
  '/favoris': 'Mes Favoris',
  '/historique': 'Historique',
  '/reputation': 'Suivi de Réputation',
  '/equipement': 'Équipement FPS — Armes & Armures',
  '/armes-vaisseaux': 'Armes de Vaisseaux — S1 à S9',
  '/evenements': 'Événements Star Citizen',
  '/outils': 'Outils Gameplay',
  '/vehicules': 'Véhicules Terrestres',
  '/composants': 'Composants Vaisseaux',
  '/locations': 'Points d\'Intérêt',
  '/minage': 'Guide Mining — Lasers, Minéraux, Vaisseaux',
  '/salvage': 'Guide Salvage',
  '/artisanat': 'Artisanat — Wikelo NPC',
  '/crafting': 'Crafting — 1044 Blueprints',
  '/engineering': 'Engineering — Dawn of Engineering',
  '/loadout': 'Loadout Builder Vaisseau',
  '/items': 'Chercheur d\'Objets',
  '/crimestat': 'CrimeStat — Système Criminel',
  '/medical': 'Mécaniques Médicales',
  '/bounty': 'Bounty Hunting — Chasse aux Primes',
  '/qt-drives': 'Quantum Drives — Comparateur',
  '/npcs': 'Base de Données PNJ',
  '/raffinerie': 'Calculateur Raffinerie',
  '/profits': 'Comparateur de Profits',
  '/commodites': 'Suivi des Commodités',
  '/assurance': 'Calculateur Assurance',
  '/fps-loadout': 'FPS Loadout Builder',
  '/spawn': 'Guide des Spawns',
  '/armures/comparer': 'Comparateur d\'Armures',
  '/dps-calc': 'Calculateur DPS',
  '/personnage': 'Suivi de Personnage',
  '/systemes-vaisseau': 'Systèmes Vaisseau — Power & Shields',
  '/piraterie': 'Guide Piraterie',
  '/lore': 'Galactapédie — Lore Star Citizen',
  '/parametres': 'Paramètres',
  '/blog': 'Blog Communautaire',
  '/builds': 'Builds Communautaires — Loadouts Partagés',
  '/master-modes': 'Master Modes — Système de Vol',
  '/prison': 'Prison — Klescher Rehabilitation',
  '/signatures': 'Signatures & Scanning — Guide Furtivité',
  '/missiles': 'Missiles & Contre-Mesures',
  '/bunkers': 'Bunkers — Missions au Sol',
  '/inventaire': 'Inventaire & Gestion d\'Équipement',
  '/vol-atmospherique': 'Vol Atmosphérique — Guide Atterrissage',
  '/checklist': 'Planificateur de Session — Checklist Quotidienne',
  '/contrebande': 'Contrebande & Marché Noir — Commerce Illégal',
  '/epaves': 'Épaves & Derelicts — Exploration',
  '/tourelles': 'Tourelles — Guide Complet',
  '/carburant': 'Calculateur Carburant — H2 & Quantum',
  '/grottes': 'Grottes & Minage FPS — Exploration Souterraine',
  '/abordage': 'Abordage de Vaisseau — Guide PvP',
  '/groupe': 'Gameplay en Groupe — Multi-Crew & Organisations',
  '/power-management': 'Power Management — Overclock & Énergie',
  '/medical-avance': 'Système Médical — Healing, Drogues & Réanimation',
  '/stamina': 'Stamina & Oxygène — Endurance & Survie',
  '/degradation': 'Dégradation & Maintenance — Usure Composants',
  '/carte': 'Carte Interactive — Stanton & Pyro',
  '/ccu': 'CCU Calculator — Chaînes d\'Upgrade Pledge',
  '/prix-historique': 'Historique des Prix — Tendances Commodités',
  '/missions/flowcharts': 'Flowcharts Missions — Arbres de Décision',
  '/routes/multi-stop': 'Route Multi-Stop — Optimiseur Cargo',
  '/minage/routes': 'Routes de Minage — Planificateur',
  '/exploration': 'Exploration & POI — Découvertes',
  '/economie': 'Événements Économiques — Impact sur les Prix',
  '/tutoriel': 'Tutoriel Interactif — Guide du Débutant',
  '/classement': 'Classement — Top Contributeurs & Builds',
  '/vaisseaux/tailles': 'Comparaison de Tailles — Vaisseaux à l\'Échelle',
  '/vaisseaux/showcase': 'Showcase Vaisseau — Vue Premium',
  '/vaisseaux/hardpoints': 'Hardpoints — Schéma d\'Armement',
  '/dps-graphs': 'DPS Graphs — Courbes Temps Réel',
  '/base-building': 'Base Building — Planificateur Cornerstone',
  '/overlay': 'SC Companion — Mode Overlay',
};

const BASE_TITLE = 'SC Companion';

export function usePageTitle() {
  const { pathname } = useLocation();

  useEffect(() => {
    const pageTitle = PAGE_TITLES[pathname];
    document.title = pageTitle
      ? `${pageTitle} | ${BASE_TITLE}`
      : BASE_TITLE;
  }, [pathname]);
}
